### ISSUE TITLE
GroopM2 installation fails

### ISSUE THREAD

**Issue by jvollme** [minillinim/GroopM#4]
In contrast to the website instructions, Pypi does not seem to contain groopM2 (or any groopM v.2 for that matter), but only the original GroopM v0.3.2.
Since GroopM2 appears to have given superiour binning results in a relatively recent review, i would like to test it, so i tried to install it from source according to the instructions on the website.
I have installed the mentioned dependencies, via conda:

    numpy >= 1.6.1
    scipy >= 0.10.1
    matplotlib >= 1.1.0
    pysam >= 0.3
    PIL >= 1.1.7
    BamM >= 1.3.0
    Cython
    GTK or TK dev packages installed on your machine

But running ```python setup.py install``` within that conda environemnt gives me many, many syntax errors and the installation just aborts.

Some examples below (can post the complete log, but it is rather large):

```SyntaxError: invalid syntax

  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/imageio-2.16.2-py2.7.egg/imageio/plugins/pillow_legacy.py", line 227
    def __init__(self, *args, plugin_id: str = None, **kwargs):
                                      ^
SyntaxError: invalid syntax

  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/imageio-2.16.2-py2.7.egg/imageio/plugins/spe.py", line 381
    n: int
     ^
SyntaxError: invalid syntax
```

or:

```
Running tables-3.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-81xfAT/tables-3.7.0/egg-dist-tmp-zc2_j8
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    'umap-learn >= 0.4.5'
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/ww5070/miniconda3/envs/groopm2_env/lib/python2.7/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-81xfAT/tables-3.7.0/setup.py", line 32
    print(f".. {kind.upper()}:: {head}")
                                      ^
SyntaxError: invalid syntax
```

**Comment by jvollme** [comment]
solution linked in #5
